name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Cobalt
        run: |
          curl -LSfs https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh | \
          sh -s -- \
          --git cobalt-org/cobalt.rs \
          --crate cobalt \
          --force \
          --target x86_64-unknown-linux-gnu \
          --tag v0.19.0
      
      - name: Build site
        run: |
          ~/.cargo/bin/cobalt build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site